baseurl = "https://tech.codeyellow.nl/"
languageCode = "en-us"
title = "CY Tech"
theme = "cy-redlounge"
copyright = "Code Yellow BV"

pygmentsCodeFences = true
#pygmentsstyle = "native"
#pygmentsuseclasses = false

[Author]
	name = "Code Yellow BV"

#[Permalinks]
#	blog = "/:year/:month/:title/"
#	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	#series = "series"
	#series-desc = "series-desc"

[params]

  sidebartitle = "Tech Blog"
  sidebartagline = "Articles about software development, interesting devops challenges, the business of software and just some other random office things"
  sidebarphoto = "/images/logo-wit.png"


[[menu.main]]
    name = "Articles"
    url = "/blog" 

[[menu.main]]
    name = "Code (Open Source)"
    url = "/code" 

[[menu.main]]
    name = "Code Yellow main site"
    url = "https://www.codeyellow.nl"

[[menu.social]]
	pre = "<i class='fa fa-2x fa-github'></i>"
    url = "https://github.com/CodeYellowBV"
    identifier = "CY Github"

[[menu.social]]
  pre = "<i class='fa fa-2x fa-bitbucket'></i>"
    url = "https://bitbucket.org/codeyellow/"
    identifier = "CY Bitbucket"